<?php

namespace mod_cpdlogbook\tables;

defined('MOODLE_INTERNAL') || die();

require_once($CFG->libdir.'/tablelib.php');

use table_sql;

class entries_table extends table_sql {

    function col_user($record) {
        global $DB;
        return fullname($DB->get_record('user', ['id' => $record->user]));
    }

    function col_time($record) {
        return userdate(time() - $record->time);
    }

    function other_cols($column, $row) {
        //return parent::other_cols($column, $row); // TODO: Change the autogenerated stub
        return NULL;
    }
}